### ISSUE TITLE
Is it possible to change user password, without remember old password?

### ISSUE THREAD

**Issue by nimblemo** [QuickBlox/Documentation#3]
Hi, we use quickblox in our application. Some functions require store user info in our databases. We want to use method reset pasword through our servers, but as wrote in your rest api, it possible if user remember his old password or he can make it through email. But we doesn't use email in user model.

Is it possible to change user password without remember old password or using email? As it work in QB web admin panel.

**Comment by soulfly** [comment]
Hi @thisroot,
to reset password via admin panel you also have to enter your current password http://image.quickblox.com/14fff8b049108319f850012e0fb4.injoit.png

I do not see other ways except current password or email.

What do you propose here?

**Comment by nimblemo** [comment]
I want to get possible, change password through api, without need remember old password.
Any way we will get path to change password. We can to save users in your servers and store they passwords in open in our servers, and then if they want to change self password we authorize they in our servers and will changing they password in your servers, but it not trusty way. 

You have way to change password without remember. This path works in our admin panel and use "admin.quickblox.com" api. is it possible to use this api on a other clients?

**Comment by nimblemo** [comment]
Can i change users passwords through admin account from api which you use for admin panel service?

**Comment by soulfly** [comment]
No you can't
