### ISSUE TITLE
Wrong signature generation 

### ISSUE THREAD

**Issue by karan23** [QuickBlox/Documentation#8]
Hi,

We have been following quickBlox documents for creating signature to be used for Rest API "https://api.quickblox.com/session.json" with body as
" {"application_id":"62009", "auth_key":"5aEUnVvFRSEfDeb", "timestamp": "1505802326", "nonce": "33533", "signature":"afb700e027914f6877809c6c3d46a5f7416a7077"}"

and response is 

 {
    "errors": {
        "base": [
            "Unexpected signature"
        ]
    }
}

The code for generating the signature is as follow in java 

public class HmacSha1Signature {
	
	public static void main(String[] args) throws Exception {
		 String signature_string ="application_id=62009&auth_key=5aEUnVvFRSEfDeb&nonce=33532&timestamp=1505802326&user[login]=9891518265&user[password]=123";
	    System.out.println(hmacDigest(signature_string, "6EESPASrHQ9VnCp", "HmacSHA1"));
	  }

	  public static String hmacDigest(String msg, String keyString, String algo) {
	    String digest = null;
	    try {
	      SecretKeySpec key = new SecretKeySpec((keyString).getBytes(), algo);
	      Mac mac = Mac.getInstance(algo);
	      mac.init(key);

	      byte[] bytes = mac.doFinal(msg.getBytes("ASCII"));

	      StringBuffer hash = new StringBuffer();
	      for (int i = 0; i < bytes.length; i++) {
	        String hex = Integer.toHexString(0xFF & bytes[i]);
	        if (hex.length() == 1) {
	          hash.append('0');
	        }
	        hash.append(hex);
	      }
	      digest = hash.toString();
	    } catch (UnsupportedEncodingException e) {
	    } catch (InvalidKeyException e) {
	    } catch (NoSuchAlgorithmException e) {
	    }
	    return digest;
	  }
	
}

Further I am attaching the screen shot of postman response. Could you please tell us what we are doing wrong to create signature?
![postman](https://user-images.githubusercontent.com/1462453/30579712-6374c7d4-9d37-11e7-8759-d620963d0bb9.png)

**Comment by tatanka987** [comment]
@karan23 please read our main documentation for REAST API about [signature generation](https://quickblox.com/developers/Authentication_and_Authorization#Signature_generation). In your case parameters in request body located not sorted alphabetically

**Comment by soulfly** [comment]
What I noticed:

In signature generation code you use user login and password
But in your Create Session request you do not pass any users params hence you receive bad signature response

Could it be a case?

**Comment by karan23** [comment]
@soulfly I tried adding user and password name but its giving me same error.please see the screen shot attached

![screenshot from 2017-09-19 15_33_31](https://user-images.githubusercontent.com/1462453/30587446-c6f98af6-9d50-11e7-9819-c25ad78b94f2.png)

**Comment by karan23** [comment]
@tatanka987 I tried the request in alphabatical order as follow
 {"application_id":"62009", "auth_key":"5aEUnVvFRSEfDeb", "nonce": "33533", "signature":"932ca490403c557448a23b982d787dc1942379a2",  "timestamp": "1505815260","user": {"login": "9891518265", "password": "123"}}
 but still same error is coming

**Comment by soulfly** [comment]
Use alphabatical order only for signature generation.
You do not need to use it in HTTP request.

your request looks correct

So I guess it's something wrong with signature generation

Do you use the same 'timestamp' and 'nonce' in signature generation and in real HTTP request?

**Comment by karan23** [comment]
@soulfly There was some difference in nonce but now I am sending the same nonce and now error has changed now status code is 401 with response 
 {
    "errors": [
        "Unauthorized"
    ]
}

**Comment by soulfly** [comment]
Great, now the sugnature is correct

"Unauthorized" means your user login or password is incorect, try to change them

**Comment by karan23** [comment]
@soulfly we have changed password and username and still same error is coming... is there any standard that quick blox follow for username and password??

**Comment by soulfly** [comment]
Did you create this user before? in Admin panel or via API

**Comment by karan23** [comment]
@soulfly No... I haven't created any user of this name

**Comment by soulfly** [comment]
That's why you receive this error

You are trying to create a session with a user but your user does not exist.

You have 2 ways:
1) Create a user in admin panel in Users module then repeat your request
2) Create a session w/o/ user via API, then create a user via API, then login with this user via API

**Comment by karan23** [comment]
@soulfly Thanks It worked..
